// Centralized Analytics Data Structure for SignSpeak AI
// Strictly distinguishes between verified project data, awaiting evaluation states,
// and informational global linguistic facts.

export const ANALYTICS_DATA = {
  // ── 1. Hero & Overall Evaluation Status ──
  status: {
    badge: 'Awaiting Verified Evaluation',
    state: 'standby', // 'standby' | 'verified' | 'in_progress'
    lastRun: null,
    environment: 'Local ONNX Runtime Web (WASM) / Client Camera',
    description: 'Evaluation, recognition behavior, dataset distribution, and real-time inference analysis.',
  },

  // ── 2. Key Performance Metrics ──
  // Null indicates unmeasured. UI automatically formats non-null numbers when evaluated.
  metrics: {
    accuracy: {
      label: 'Overall Accuracy',
      value: null,
      unit: '%',
      decimals: 1,
      description: 'Aggregate top-1 recognition accuracy across multi-signer validation sets.',
      status: 'Not Yet Measured',
    },
    precision: {
      label: 'Precision',
      value: null,
      unit: '%',
      decimals: 1,
      description: 'Macro-averaged precision quantifying positive predictive reliability across all classes.',
      status: 'Not Yet Measured',
    },
    recall: {
      label: 'Recall',
      value: null,
      unit: '%',
      decimals: 1,
      description: 'Macro-averaged sensitivity capturing true positive detection coverage.',
      status: 'Not Yet Measured',
    },
    f1: {
      label: 'F1 Score',
      value: null,
      unit: '%',
      decimals: 1,
      description: 'Harmonic mean of precision and recall balancing false alarms and missed gestures.',
      status: 'Not Yet Measured',
    },
    latency: {
      label: 'Inference Latency',
      value: null,
      unit: 'ms',
      decimals: 0,
      description: 'End-to-end frame processing time from webcam frame arrival to predicted class.',
      status: 'Not Yet Measured',
    },
  },

  // ── 3. Dataset Analysis (Verified Project Data) ──
  dataset: {
    verifiedSource: 'Kaggle grassknoted/asl-alphabet',
    sourceUrl: 'https://www.kaggle.com/datasets/grassknoted/asl-alphabet',
    totalSamples: 11742,
    classesCount: 26,
    trainSamples: null, // Not recorded in project metadata
    valSamples: null,   // Not recorded in project metadata
    testSamples: null,  // Not recorded in project metadata
    splitMethodology: 'Not recorded / Multi-signer split pending formal protocol',
    windowSize: 12,
    landmarkDimensions: 63, // 21 landmarks * 3 coordinates (x, y, z)
    notes: 'Static letter images repeated WINDOW=12 times to form temporal sequences. Lexical word signs (HELLO, SORRY, YES) are evaluated separately via synthetic heuristic extensions.',
    samplesPerClass: {
      A: 455,
      B: 438,
      C: 489,
      D: 494,
      E: 459,
      F: 489,
      G: 475,
      H: 479,
      I: 469,
      J: 445,
      K: 498,
      L: 436,
      M: 290,
      N: 166,
      O: 487,
      P: 495,
      Q: 481,
      R: 480,
      S: 500,
      T: 462,
      U: 457,
      V: 452,
      W: 411,
      X: 449,
      Y: 491,
      Z: 495,
    },
  },

  // ── 4. Class-wise Recognition Analysis (A-Z) ──
  // Contains class details; accuracy metrics remain null until verified test run.
  classPerformance: [
    { label: 'A', handshape: 'Closed fist, thumb flat against index side', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'B', handshape: 'Four upright fingers together, thumb flat on palm', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'C', handshape: 'Curved fingers and thumb forming an open C curve', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'D', handshape: 'Index finger upright, thumb touching curled middle/ring/pinky', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'E', handshape: 'Fingers curled tightly down resting over tucked thumb', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'F', handshape: 'Index and thumb touching in circle, remaining 3 fingers spread', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'G', handshape: 'Index points horizontally forward, thumb held parallel', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'H', handshape: 'Index and middle extended forward horizontally together', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'I', handshape: 'Pinky finger extended upright, remaining fingers in fist', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'J', handshape: 'Pinky extended upright tracing a swooping J curve in air', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'K', handshape: 'Index upright, middle angled forward, thumb between', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'L', handshape: 'Index upright, thumb extended horizontally at 90 degrees', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'M', handshape: 'Three fingers draped forward over tucked thumb', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'N', handshape: 'Two fingers draped forward over tucked thumb', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'O', handshape: 'All fingertips curved inward meeting the thumb tip', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'P', handshape: 'Downward angled K handshape pointing index forward', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'Q', handshape: 'Downward pointing G handshape with thumb parallel', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'R', handshape: 'Index and middle fingers crossed upright', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'S', handshape: 'Solid fist with thumb wrapped across front of fingers', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'T', handshape: 'Thumb tucked securely between index and middle fingers', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'U', handshape: 'Index and middle fingers held upright together', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'V', handshape: 'Index and middle fingers held upright spread apart (peace)', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'W', handshape: 'Index, middle, and ring fingers spread upright', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'X', handshape: 'Index finger hooked / bent at knuckle joint in fist', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'Y', handshape: 'Thumb and pinky extended wide with middle fingers curled', accuracy: null, precision: null, recall: null, f1: null },
    { label: 'Z', handshape: 'Index finger extended tracing a dynamic Z in air', accuracy: null, precision: null, recall: null, f1: null },
  ],

  // ── 5. Confusion Matrix (26x26) ──
  confusionMatrix: {
    labels: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
    data: null, // Null until verified test run produces actual counts
    statusMessage: 'Confusion matrix will appear after verified test-set evaluation.',
  },

  // ── 6. Training Performance ──
  trainingHistory: {
    epochs: null,
    trainAccuracy: null,
    valAccuracy: null,
    trainLoss: null,
    valLoss: null,
    lossFunction: 'Categorical Crossentropy',
    optimizer: 'Adam (lr=0.001)',
    statusMessage: 'Training history not available',
    architecture: 'MediaPipe 21 Landmarks (63D) → 1D Normalization → Dense/LSTM Feature Fusion → 26-Class Softmax',
  },

  // ── 7. Real-Time Inference Performance ──
  inference: {
    fps: null,
    avgLatencyMs: null,
    p95LatencyMs: null,
    confidence: null,
    statusMessage: 'Real-time metrics stream during active camera interpreter session.',
    pipelineStages: [
      { step: '1. Frame Ingestion', detail: 'HTML5 Video capture 640×480 @ 30 FPS', targetLatency: '< 4ms' },
      { step: '2. Landmark Extraction', detail: 'MediaPipe HandLandmarker WASM (21 points)', targetLatency: '< 18ms' },
      { step: '3. Coordinate Normalization', detail: 'Wrist-relative translation & bounding-box scale', targetLatency: '< 1ms' },
      { step: '4. ONNX Inference', detail: 'ONNX Runtime Web SIMD WebAssembly kernel', targetLatency: '< 12ms' },
      { step: '5. Temporal Stabilization', detail: 'Multi-frame hysteresis gating (window: 4, conf > 0.75)', targetLatency: '< 1ms' },
    ],
    sampleTimeline: [
      { frame: 'Frame 01', raw: 'A', confidence: 0.71, status: 'gating', label: 'Candidate detected' },
      { frame: 'Frame 02', raw: 'A', confidence: 0.78, status: 'smoothing', label: 'Buffer accumulating' },
      { frame: 'Frame 03', raw: 'A', confidence: 0.84, status: 'smoothing', label: 'Confidence threshold passed' },
      { frame: 'Frame 04', raw: 'A', confidence: 0.91, status: 'stabilized', label: 'Temporal threshold met' },
      { frame: 'Frame 05', raw: 'A', confidence: 0.94, status: 'committed', label: 'Prediction committed' },
    ],
  },

  // ── 8. Prediction Stability ──
  stability: {
    recordedSequence: null,
    statusMessage: 'Stability analysis requires a recorded prediction sequence from a live evaluation session.',
    mechanism: {
      windowSize: 4,
      threshold: 0.75,
      description: 'A sliding temporal queue requires consistent class output across consecutive frames before emitting a prediction, suppressing transient hand landmark jitter.',
    },
  },

  // ── 9. Error Analysis ──
  errors: {
    mostChallengingClasses: null,
    commonConfusions: null,
    statusMessage: 'Error analysis unavailable until test-set evaluation is completed.',
    knownTopologicalChallenges: [
      { pair: ['M', 'N'], reason: 'Thumb placement under 3 vs 2 folded fingers produces near-identical 2D landmark projections.' },
      { pair: ['A', 'S'], reason: 'Fist silhouette difference depends solely on thumb crossing the front vs resting alongside index.' },
      { pair: ['K', 'V'], reason: 'Thumb resting on the middle finger joint can be occluded depending on camera viewpoint angle.' },
      { pair: ['E', 'O'], reason: 'Curled fingertips near thumb tip share similar bounding radius and knuckle angles.' },
    ],
  },

  // ── 10. Evaluation Methodology ──
  methodology: {
    dataset: 'Kaggle ASL Alphabet stills (grassknoted/asl-alphabet)',
    datasetSize: '11,742 samples across 26 alphabet classes (A–Z)',
    trainSplit: 'Not recorded',
    valSplit: 'Not recorded',
    testSplit: 'Not recorded',
    classesCount: '26 alphabet letters + heuristic fallback word gestures',
    metrics: 'Top-1 Accuracy, Macro-averaged Precision, Macro-averaged Recall, Macro F1, P95 Inference Latency',
    webcamTesting: 'In-browser local inference via ONNX Runtime Web WASM + MediaPipe HandLandmarker',
    realTimeEvaluation: 'Frame-by-frame measurement of camera capture, 21-point tracking, normalization, forward pass, and buffer smoothing',
  },

  // ── 11. Global Sign Language Landscape (Linguistic Facts, NOT user statistics) ──
  landscape: {
    title: 'Global Sign Language Landscape',
    subtitle: 'Sign languages are diverse linguistic systems used across communities worldwide.',
    disclaimer: 'Informational global linguistic references sourced from the World Federation of the Deaf (WFD) and Ethnologue. Not user tracking data.',
    primaryHub: {
      id: 'isl-blr',
      name: 'Bengaluru, India',
      language: 'Indian Sign Language (ISL)',
      code: 'ins',
      family: 'Indo-Pakistani Sign Language family',
      region: 'South Asia',
      context: 'SignSpeak AI research & development base. ISL is used by an estimated 1.5–6M deaf individuals across the subcontinent.',
      coords: [77.5946, 12.9716],
      x: 708.84,
      y: 205.37,
      isPrimary: true,
    },
    languages: [
      {
        id: 'isl',
        name: 'India',
        language: 'Indian Sign Language (ISL)',
        code: 'ins',
        family: 'Indo-Pakistani',
        signersApprox: '~1.5M - 6M',
        notes: 'SignSpeak AI project inception location. ISL possesses its own independent grammar, syntax, and regional variations across Indian states.',
        coords: [77.5946, 12.9716],
        x: 708.84,
        y: 205.37,
        isPrimary: true,
      },
      {
        id: 'asl',
        name: 'United States',
        language: 'American Sign Language (ASL)',
        code: 'ase',
        family: 'French Sign Language family',
        signersApprox: '~500K - 1M',
        notes: 'Source system for the bundled A–Z alphabet recognition model. Developed in the early 19th century with significant French Sign Language roots.',
        coords: [-74.006, 40.7128],
        x: 315.4,
        y: 117.9,
      },
      {
        id: 'bsl',
        name: 'United Kingdom',
        language: 'British Sign Language (BSL)',
        code: 'bfi',
        family: 'BANZSL (British, Australian, New Zealand)',
        signersApprox: '~150K',
        notes: 'Distinct from ASL despite common spoken language; utilizes a two-handed manual fingerspelling alphabet.',
        coords: [-0.1278, 51.5074],
        x: 499.7,
        y: 84.64,
      },
      {
        id: 'lsf',
        name: 'France',
        language: 'French Sign Language (LSF)',
        code: 'fsl',
        family: 'French Sign Language family',
        signersApprox: '~100K - 200K',
        notes: 'Historical ancestor of American Sign Language through Laurent Clerc and Thomas Hopkins Gallaudet.',
        coords: [2.3522, 48.8566],
        x: 505.63,
        y: 92.68,
      },
      {
        id: 'dgs',
        name: 'Germany',
        language: 'German Sign Language (DGS)',
        code: 'gsg',
        family: 'German Sign Language family',
        signersApprox: '~80K - 200K',
        notes: 'Officially recognized under the German Federal Equality Act (2002). Features distinct mouth gestures (Mundbilder).',
        coords: [8.6821, 50.1109],
        x: 520.62,
        y: 88.87,
      },
      {
        id: 'jsl',
        name: 'Japan',
        language: 'Japanese Sign Language (JSL)',
        code: 'jsl',
        family: 'Japanese Sign Language family',
        signersApprox: '~300K',
        notes: 'Features fingerspelling (Yubimoji) based on Japanese syllabary (kana) rather than Latin alphabet.',
        coords: [139.6917, 35.6895],
        x: 855.75,
        y: 133.68,
      },
      {
        id: 'libras',
        name: 'Brazil',
        language: 'Brazilian Sign Language (Libras)',
        code: 'bzs',
        family: 'French Sign Language family',
        signersApprox: '~2M - 3M',
        notes: 'Granted official legal status by Brazilian Federal Law 10.436 in 2002.',
        coords: [-46.6333, -23.5505],
        x: 376.8,
        y: 320.18,
      },
      {
        id: 'auslan',
        name: 'Australia',
        language: 'Australian Sign Language (Auslan)',
        code: 'asf',
        family: 'BANZSL family',
        signersApprox: '~20K - 30K',
        notes: 'Closely related to British and New Zealand Sign Languages; uses two-handed manual fingerspelling.',
        coords: [151.2093, -33.8688],
        x: 887.66,
        y: 352.78,
      },
      {
        id: 'sasl',
        name: 'South Africa',
        language: 'South African Sign Language (SASL)',
        code: 'sfs',
        family: 'Independent / BANZSL influenced',
        signersApprox: '~230K - 500K',
        notes: 'Signed into constitutional law as the 12th official national language of South Africa in July 2023.',
        coords: [28.0473, -26.2041],
        x: 573.62,
        y: 328.56,
      },
      {
        id: 'csla',
        name: 'Egypt',
        language: 'Egyptian Sign Language (ESL)',
        code: 'esl',
        family: 'Arab Sign Language family',
        signersApprox: '~1.5M - 2M',
        notes: 'Widely used in the Nile basin region; actively documented by linguistic researchers in Cairo.',
        coords: [31.2357, 30.0444],
        x: 581.1,
        y: 151.51,
      },
    ],
    linguisticConnections: [
      { from: 'lsf', to: 'asl', label: 'LSF → ASL (Historical Lineage, 1817)', duration: 4.5 },
      { from: 'bsl', to: 'auslan', label: 'BANZSL Shared Lineage', duration: 5.5 },
      { from: 'isl', to: 'asl', label: 'Cross-Linguistic Benchmarking', duration: 5.0 },
      { from: 'lsf', to: 'libras', label: 'French Sign Lineage in South America', duration: 4.8 },
      { from: 'isl', to: 'bsl', label: 'Fingerspelling Structural Contrast', duration: 4.2 },
    ],
    globalFacts: [
      { value: '300+', label: 'Distinct Sign Languages', note: 'Independent natural languages with full grammar' },
      { value: '70M+', label: 'Deaf People Globally', note: 'World Federation of the Deaf (WFD) census' },
      { value: '80%+', label: 'Reside in Developing Countries', note: 'Heightened need for accessible vision tech' },
      { value: '21', label: '3D Hand Keypoints', note: 'MediaPipe tracking resolution per frame' },
    ],
  },
};
